name       : neon
version    : 0.32.2
release    : 7
source     :
    - https://notroj.github.io/neon/neon-0.32.2.tar.gz : 986566468c6295fc5d0fb141a5981e31c9f82ee38e938374abed8471ef2fb286
license    : LGPL-3.0-or-later
component  : network.library
homepage   : https://notroj.github.io/neon/
summary    : neon is an HTTP and WebDAV client library
description: |
    neon is an HTTP and WebDAV client library, with a C interface.
setup      : |
    %configure --enable-shared --with-ssl --disable-static
build      : |
    %make
install    : |
    %make_install
