name       : neon
version    : 0.31.2
release    : 5
source     :
    - https://notroj.github.io/neon/neon-0.31.2.tar.gz : cf1ee3ac27a215814a9c80803fcee4f0ede8466ebead40267a9bd115e16a8678
license    : LGPL-3.0-or-later
component  : network.library
homepage   : https://notroj.github.io/neon/
summary    : neon is an HTTP and WebDAV client library
description: |
    neon is an HTTP and WebDAV client library, with a C interface.
setup      : |
    %configure --enable-shared --with-ssl --disable-static
build      : |
    %make
install    : |
    %make_install
