name       : neon
version    : 0.30.2
release    : 4
source     :
    - http://www.webdav.org/neon/neon-0.30.2.tar.gz : db0bd8cdec329b48f53a6f00199c92d5ba40b0f015b153718d1b15d3d967fbca
license    : LGPL-3.0-or-later
component  : network.library
summary    : neon is an HTTP and WebDAV client library
description: |
    neon is an HTTP and WebDAV client library, with a C interface.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --prefix=/usr --enable-shared --with-ssl --disable-static
build      : |
    %make
install    : |
    %make_install
