name       : neon
version    : 0.32.5
release    : 8
source     :
    - https://notroj.github.io/neon/neon-0.32.5.tar.gz : 4872e12f802572dedd4b02f870065814b2d5141f7dbdaf708eedab826b51a58a
license    : LGPL-3.0-or-later
component  : network.library
homepage   : https://notroj.github.io/neon/
summary    : neon is an HTTP and WebDAV client library
description: |
    neon is an HTTP and WebDAV client library, with a C interface.
setup      : |
    %configure --enable-shared --with-ssl --disable-static
build      : |
    %make
install    : |
    %make_install
