name       : neon
version    : 0.30.1
release    : 2
source     :
    - http://www.webdav.org/neon/neon-0.30.1.tar.gz : 00c626c0dc18d094ab374dbd9a354915bfe4776433289386ed489c2ec0845cdd
license    : LGPL-3.0 
summary    : neon is an HTTP and WebDAV client library
description: |
    neon is an HTTP and WebDAV client library, with a C interface.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --prefix=/usr --enable-shared --with-ssl --disable-static
build      : |
    %make
install    : |
    %make_install
